# theme: jekyll-theme-cayman
# remote_theme: mmistakes/minimal-mistakes
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
layout: default
markdown: kramdown
title: lewinschmitt.github.io
description: Welcome to my website
show_downloads: "true"
plugins:
  - jekyll-include-cache
