# theme: jekyll-theme-cayman
# remote_theme: mmistakes/minimal-mistakes
layout: default
markdown: kramdown
title: lewinschmitt.github.io
description: Welcome to my website
show_downloads: "true"
plugins:
  - jekyll-include-cach
